package com.forecast.models.inventory;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * ReplenishmentRecommendation represents an inventory replenishment recommendation
 * generated by integrating forecast results with current inventory levels.
 *
 * This model bridges the demand forecasting system with inventory management,
 * providing actionable recommendations for stock replenishment decisions.
 */
public class ReplenishmentRecommendation {

    private String productId;
    private String locationId;
    private String storeId;

    // Current inventory state
    private int currentStock;
    private int reservedQuantity;
    private int availableQuantity;
    private int safetyStockLevel;
    private int reorderThreshold;

    // Forecast-based metrics
    private BigDecimal forecastedAverageDemand;
    private BigDecimal forecastedPeakDemand;
    private BigDecimal confidenceIntervalLower;
    private BigDecimal confidenceIntervalUpper;
    private LocalDate forecastStartDate;
    private LocalDate forecastEndDate;

    // Recommendation details
    private int recommendedOrderQuantity;
    private LocalDate recommendedOrderDate;
    private LocalDate recommendedDeliveryDate;
    private int daysUntilStockout;
    private String urgencyLevel; // CRITICAL, HIGH, MEDIUM, LOW
    private String rationale;

    // Metadata
    private LocalDate generatedDate;
    private String modelUsed;
    private double confidence; // 0.0 to 1.0
    private boolean approved;

    public ReplenishmentRecommendation() {}

    public ReplenishmentRecommendation(String productId, String locationId, String storeId) {
        this.productId = productId;
        this.locationId = locationId;
        this.storeId = storeId;
        this.generatedDate = LocalDate.now();
    }

    // Getters and Setters

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getLocationId() {
        return locationId;
    }

    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    public String getStoreId() {
        return storeId;
    }

    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    public int getCurrentStock() {
        return currentStock;
    }

    public void setCurrentStock(int currentStock) {
        this.currentStock = currentStock;
    }

    public int getReservedQuantity() {
        return reservedQuantity;
    }

    public void setReservedQuantity(int reservedQuantity) {
        this.reservedQuantity = reservedQuantity;
    }

    public int getAvailableQuantity() {
        return availableQuantity;
    }

    public void setAvailableQuantity(int availableQuantity) {
        this.availableQuantity = availableQuantity;
    }

    public int getSafetyStockLevel() {
        return safetyStockLevel;
    }

    public void setSafetyStockLevel(int safetyStockLevel) {
        this.safetyStockLevel = safetyStockLevel;
    }

    public int getReorderThreshold() {
        return reorderThreshold;
    }

    public void setReorderThreshold(int reorderThreshold) {
        this.reorderThreshold = reorderThreshold;
    }

    public BigDecimal getForecastedAverageDemand() {
        return forecastedAverageDemand;
    }

    public void setForecastedAverageDemand(BigDecimal forecastedAverageDemand) {
        this.forecastedAverageDemand = forecastedAverageDemand;
    }

    public BigDecimal getForecastedPeakDemand() {
        return forecastedPeakDemand;
    }

    public void setForecastedPeakDemand(BigDecimal forecastedPeakDemand) {
        this.forecastedPeakDemand = forecastedPeakDemand;
    }

    public BigDecimal getConfidenceIntervalLower() {
        return confidenceIntervalLower;
    }

    public void setConfidenceIntervalLower(BigDecimal confidenceIntervalLower) {
        this.confidenceIntervalLower = confidenceIntervalLower;
    }

    public BigDecimal getConfidenceIntervalUpper() {
        return confidenceIntervalUpper;
    }

    public void setConfidenceIntervalUpper(BigDecimal confidenceIntervalUpper) {
        this.confidenceIntervalUpper = confidenceIntervalUpper;
    }

    public LocalDate getForecastStartDate() {
        return forecastStartDate;
    }

    public void setForecastStartDate(LocalDate forecastStartDate) {
        this.forecastStartDate = forecastStartDate;
    }

    public LocalDate getForecastEndDate() {
        return forecastEndDate;
    }

    public void setForecastEndDate(LocalDate forecastEndDate) {
        this.forecastEndDate = forecastEndDate;
    }

    public int getRecommendedOrderQuantity() {
        return recommendedOrderQuantity;
    }

    public void setRecommendedOrderQuantity(int recommendedOrderQuantity) {
        this.recommendedOrderQuantity = recommendedOrderQuantity;
    }

    public LocalDate getRecommendedOrderDate() {
        return recommendedOrderDate;
    }

    public void setRecommendedOrderDate(LocalDate recommendedOrderDate) {
        this.recommendedOrderDate = recommendedOrderDate;
    }

    public LocalDate getRecommendedDeliveryDate() {
        return recommendedDeliveryDate;
    }

    public void setRecommendedDeliveryDate(LocalDate recommendedDeliveryDate) {
        this.recommendedDeliveryDate = recommendedDeliveryDate;
    }

    public int getDaysUntilStockout() {
        return daysUntilStockout;
    }

    public void setDaysUntilStockout(int daysUntilStockout) {
        this.daysUntilStockout = daysUntilStockout;
    }

    public String getUrgencyLevel() {
        return urgencyLevel;
    }

    public void setUrgencyLevel(String urgencyLevel) {
        this.urgencyLevel = urgencyLevel;
    }

    public String getRationale() {
        return rationale;
    }

    public void setRationale(String rationale) {
        this.rationale = rationale;
    }

    public LocalDate getGeneratedDate() {
        return generatedDate;
    }

    public void setGeneratedDate(LocalDate generatedDate) {
        this.generatedDate = generatedDate;
    }

    public String getModelUsed() {
        return modelUsed;
    }

    public void setModelUsed(String modelUsed) {
        this.modelUsed = modelUsed;
    }

    public double getConfidence() {
        return confidence;
    }

    public void setConfidence(double confidence) {
        this.confidence = Math.max(0.0, Math.min(1.0, confidence));
    }

    public boolean isApproved() {
        return approved;
    }

    public void setApproved(boolean approved) {
        this.approved = approved;
    }

    @Override
    public String toString() {
        return "ReplenishmentRecommendation{" +
                "productId='" + productId + '\'' +
                ", locationId='" + locationId + '\'' +
                ", currentStock=" + currentStock +
                ", recommendedOrderQuantity=" + recommendedOrderQuantity +
                ", urgencyLevel='" + urgencyLevel + '\'' +
                ", daysUntilStockout=" + daysUntilStockout +
                ", approved=" + approved +
                '}';
    }
}
